"""The frozen OpenAPI document is regenerated by a script, never retyped.

`scripts/write_openapi_frozen.py` is the only writer of
`tests/api/openapi_frozen.json`; `tests/api/test_openapi.py` pins that the
tracked file matches what it produces today. This suite pins the script's own
two guarantees instead: regenerating twice yields the same bytes, and
`--check` reports a document that has drifted from the file on disk.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

from scripts.write_openapi_frozen import (
    diff_report,
    frozen_document_path,
    main,
    regenerate_frozen_document,
)

STALE_OPENAPI_VERSION = '"openapi": "9.9.9"'
CURRENT_OPENAPI_VERSION = '"openapi": "3.1.0"'


def mutated(frozen_path: Path) -> str:
    text = frozen_path.read_text(encoding="utf-8")
    assert CURRENT_OPENAPI_VERSION in text
    return text.replace(CURRENT_OPENAPI_VERSION, STALE_OPENAPI_VERSION)


def test_regenerating_a_fresh_tree_twice_is_idempotent(tmp_path: Path) -> None:
    frozen_path = tmp_path / "openapi_frozen.json"

    regenerate_frozen_document(frozen_path)
    first_write = frozen_path.read_text(encoding="utf-8")
    regenerate_frozen_document(frozen_path)

    assert frozen_path.read_text(encoding="utf-8") == first_write
    assert diff_report(frozen_path) is None


def test_diff_report_names_the_first_differing_path_and_line_counts(
    tmp_path: Path,
) -> None:
    frozen_path = tmp_path / "openapi_frozen.json"
    regenerate_frozen_document(frozen_path)
    frozen_path.write_text(mutated(frozen_path), encoding="utf-8")

    problem = diff_report(frozen_path)

    assert problem is not None
    assert "is stale" in problem
    assert "openapi" in problem
    assert "line(s) added" in problem
    assert "line(s) removed" in problem


def test_main_check_exits_red_only_after_the_document_drifts(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.chdir(tmp_path)
    frozen_path = frozen_document_path(tmp_path)

    monkeypatch.setattr(sys, "argv", ["write_openapi_frozen.py"])
    assert main() == 0
    capsys.readouterr()

    monkeypatch.setattr(sys, "argv", ["write_openapi_frozen.py", "--check"])
    assert main() == 0

    frozen_path.write_text(mutated(frozen_path), encoding="utf-8")

    assert main() == 1
    assert "is stale" in capsys.readouterr().err
